### ISSUE TITLE
更新到0.0.3后打不开了

### ISSUE THREAD

**Issue by Kurt-Shiwz** [maotoumao/MusicFreeDesktop#71]
macos：14.2.1 
m1 pro
musicFreeDesktop:0.0.3

A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

dlopen(/Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
Referenced from: <EEFDBDF1-FBAA-3A94-BD2F-9CA58F0F338C> /Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
Reason: tried: '/Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/build/Release/../.././vendor/8.14.5/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/build/Release/../.././vendor/8.14.5/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/MusicFree.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvips-cpp.42.dylib' (no such file), '/Applications/MusicFree.app/Contents/Frameworks/libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file, not in dyld cache)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/lib/sharp.js:37:9)
at Module._compile (node:internal/modules/cjs/loader:1269:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
at Module.load (node:internal/modules/cjs/loader:1124:32)
at Module._load (node:internal/modules/cjs/loader:965:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1148:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/Applications/MusicFree.app/Contents/Resources/app/node_modules/sharp/lib/constructor.js:11:1)
at Module._compile (node:internal/modules/cjs/loader:1269:14)

**Comment by maotoumao** [comment]
更新了下打包文件，重新下载试试吧~
