### ISSUE TITLE
macOS v13.5 node v18.17打包出现错误

### ISSUE THREAD

**Issue by djapple** [maotoumao/MusicFreeDesktop#8]
```bash
git clone https://github.com/maotoumao/MusicFreeDesktop.git
```
进入MusicFreeDesktop文件夹 执行：
```bash
npm install
npm run make 或者 npm run package
```
生成的文件在根目录的out文件夹下

_Originally posted by @maotoumao in https://github.com/maotoumao/MusicFreeDesktop/issues/2#issuecomment-1653700133_

npm install出现错误            

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm ERR! code 1
npm ERR! path /Users/yy.feng/Downloads/MusicFreeDesktop-master/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: socket hang up
npm ERR!     at ClientRequest.<anonymous> (/Users/yy.feng/Downloads/MusicFreeDesktop-master/node_modules/got/dist/source/core/index.js:970:111)
npm ERR!     at Object.onceWrapper (node:events:629:26)
npm ERR!     at ClientRequest.emit (node:events:526:35)
npm ERR!     at origin.emit (/Users/yy.feng/Downloads/MusicFreeDesktop-master/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
npm ERR!     at TLSSocket.socketOnEnd (node:_http_client:525:9)
npm ERR!     at TLSSocket.emit (node:events:526:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1359:12)
npm ERR!     at connResetException (node:internal/errors:720:14)
npm ERR!     at TLSSocket.socketOnEnd (node:_http_client:525:23)
npm ERR!     at TLSSocket.emit (node:events:526:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1359:12)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm ERR! A complete log of this run can be found in: /Users/yy.feng/.npm/_logs/2023-08-01T12_48_19_973Z-debug-0.log

**Comment by djapple** [comment]
尝试换源，开VPN还是出现一样的情况，搞不定了，有时间打包一个MACOS版本好吗

**Comment by xinatcg** [comment]
自己手动 build 的包: https://github.com/xinatcg/MusicFreeDesktop/releases/tag/v0.0.0-manual-build
后面有时间加个 github action 自动化
